spring:
    application:
        name: OG-ExpSafetyPlatform

    datasource:
        url: jdbc:mysql://localhost:3305/og-expsafetyplatform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Zheng200610
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: Asia/Shanghai
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
