spring:
    application:
        name: OG-ExpSafetyPlatform

    datasource:
        url: jdbc:mysql://localhost:3306/ogexpsafetyplatform?userUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: gnah060725
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: Asia/Shanghai
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-delete-field: deleted
            logic-delete-value: 1
            logic-not-delete-value: 0

